name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.1
    - name: Set up JDK 25
      uses: actions/setup-java@v5.1.0
      with:
          distribution: 'oracle'
          java-version: '25'
          cache: 'maven'
    - name: reverseTest
      id: reverseTest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: reverseTest
        setup-command: ''
        command: mvn -Dtest=TestAssignment#reverseTest test
        timeout: 10
        max-score: 10
    - name: insertAtStartTest
      id: insertAtStartTest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: insertAtStartTest
        setup-command: ''
        command: mvn -Dtest=TestAssignment#insertAtStartTest test
        timeout: 10
        max-score: 5
    - name: insertAtEndTest
      id: insertAtEndTest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: insertAtEndTest
        setup-command: ''
        command: mvn -Dtest=TestAssignment#insertAtEndTest test
        timeout: 10
        max-score: 5
    - name: insertAtIndexTest
      id: insertAtIndexTest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: insertAtIndexTest
        setup-command: ''
        command: mvn -Dtest=TestAssignment#insertAtIndexTest test
        timeout: 10
        max-score: 5
    - name: deleteAtStartTest
      id: deleteAtStartTest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: deleteAtStartTest
        setup-command: ''
        command: mvn -Dtest=TestAssignment#deleteAtStartTest test
        timeout: 10
        max-score: 5
    - name: deleteAtEndTest
      id: deleteAtEndTest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: deleteAtEndTest
        setup-command: ''
        command: mvn -Dtest=TestAssignment#deleteAtEndTest test
        timeout: 10
        max-score: 5
    - name: deleteAtIndexTest
      id: deleteAtIndexTest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: deleteAtIndexTest
        setup-command: ''
        command: mvn -Dtest=TestAssignment#deleteAtIndexTest test
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        REVERSETEST_RESULTS: "${{steps.reverseTest.outputs.result}}"
        INSERTATSTARTTEST_RESULTS: "${{steps.insertAtStartTest.outputs.result}}"
        INSERTATENDTEST_RESULTS: "${{steps.insertAtEndTest.outputs.result}}"
        INSERTATINDEXTEST_RESULTS: "${{steps.insertAtIndexTest.outputs.result}}"
        DELETEATSTARTTEST_RESULTS: "${{steps.deleteAtStartTest.outputs.result}}"
        DELETEATENDTEST_RESULTS: "${{steps.deleteAtEndTest.outputs.result}}"
        DELETEATINDEXTEST_RESULTS: "${{steps.deleteAtIndexTest.outputs.result}}"
      with:
        runners: reverseTest,insertAtStartTest,insertAtEndTest,insertAtIndexTest,deleteAtStartTest,deleteAtEndTest,deleteAtIndexTest
